elk/urls.py
from django.urls import path, include

from elk import views

urlpatterns = [
    path('', views.ViewTheObjects.as_view(), name='list'),
    path('view/<slug:pk>/', views.SomeObjectInfo.as_view(), name='details'),
    path('new/', views.CreateSomeObject.as_view(), name='create'),
    path('view/<slug:pk>/delete/', views.DeleteSomeObject.as_view(), name='delete'),
    path('404', views.not_found, name='404'),
    path('500', views.internal_error, name='500'),
]

hwdj/urls.py
from django.urls import path, include

from hw import views as hw_views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', hw_views.index),
    path('elk/', include(('elk.urls', 'elk'), namespace='elk')),
]

elk/models.py
from django.db.models import Model, fields


# Create your models here.

class SomeObject(Model):
    creation = fields.DateTimeField(auto_now_add=True)
    update = fields.DateTimeField(auto_now=True)
    content = fields.CharField(max_length=256)

hw/models.py
from django.db import models

# Create your models here.

elk/views.py
import django.views.generic as views
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from elk.models import SomeObject


# Create your views here.

class CreateSomeObject(views.CreateView):
    model = SomeObject
    fields = ['content']
    template_name = 'elk/create.html'

    def get_success_url(self):
        return reverse_lazy('elk:details', args=(self.object.id,))


class ViewTheObjects(views.ListView):
    model = SomeObject
    template_name = 'elk/list.html'


class SomeObjectInfo(views.DetailView):
    model = SomeObject
    template_name = 'elk/item.html'


class DeleteSomeObject(DeleteView):
    model = SomeObject
    success_url = reverse_lazy('elk:list')
    template_name = 'elk/item.html'
    extra_context = {'confirm_delete': True}


def not_found(_):
    return Http404()


def internal_error(_):
    raise Exception("This error should be logged.")

hw/views.py
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render

import os
import environ
import random
from time import sleep
from django.http import Http404


# Create your views here.


def index(request):
    value = random.uniform(0, 3)
    if value < 1:
        raise Http404
    if value > 2.5:
        print(request['gimme a 500'])
    sleep(random.uniform(1, 5))
    return HttpResponse("Hello, world. %s %s %s %s" % (
        value, settings.TEST_VALUE, os.environ.get('TEST_VALUE', 'not found'),
        os.environ.get('TEST_VALUE2', 'not found')))

elk/templates/elk/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Object</title>
</head>
<body>
    <h1>New Object</h1>
    <form action="{% url 'elk:create' %}" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Create">
    </form>
    {% if obj %}
        <p>Created: {{ obj.content }}</p>
    {% endif %}

</body>
</html>

elk/templates/elk/item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your object</title>
</head>
<body>
<h1>{{ object.id }} ~ {{ object.content }}</h1>
<br>
<p>Created: {{ object.creation }}</p>
<p>Updated: {{ object.update }}</p>
<br>
{% if confirm_delete %}
<p>Are you sure?</p>
<form action="{% url 'elk:delete' object.id %}" method="post">
    <input type="submit" value="Yes">
    <a href="{% url 'elk:details' object.id %}">No</a>
    {% csrf_token %}
</form>
{% else %}
<a href="{% url 'elk:delete' object.id %}">Delete</a>
{% endif %}
<hr>
<a href="{% url 'elk:list' %}">Go back</a>
</body>
</html>

elk/templates/elk/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Objects</title>
</head>
<body>
<h1>Your objects</h1>
<p>
    <a href="{% url 'elk:create' %}">Create new</a>
</p>
<hr>
<ul>
    {% for o in object_list %}
        <li><p>{{ o.content }}</p>
            <p>
                <a href="{% url 'elk:details' o.id %}">View</a>
                <a href="{% url 'elk:delete' o.id %}">Delete</a>
            </p>
        </li>
    {% empty %}
        <p>No objects yet.</p>
    {% endfor %}
</ul>
</body>
</html>